Map<String, String> enUS = {
  "e-radauti": "e-Radauti",
  "app-radauti": "e-Raduti App",
  "developed-by":
      "Application developed through the efforts of the Rădăutiul Civic Association",
  "welcome": "Welcome!",
  "weak-password": "The password is weak. Please provide a better password",
  "user-not-found": "We couldn't an account with the given credentials",
  "invalid-email": "The email is invalid",
  "user-disabled": "The account is disabled",
  "email-already-in-use": "The account with the given email is already in use",
  "invalid-credential": "The credentials are invalid or they have expired",
  "wrong-password": "The password is wrong",
  "invalid-verification-code": "The verification code is invalid",
  "invalid-verification-id": "The verification ID is invalid",
  "password-mismatch": "The old password doesn't match",
  "user-mismatch":
      "The credential given does not correspond to the current user",
  "expired-action-code": "The code has expired",
  "my-account": "My account",
  "report-problem": "Report a problem",
  "local-administration": "Local administration",
  "events": "Events",
  "usefull-numbers": "Usefull numbers",
  "announces": "Announces",
  "air-quality": "Air quality",
  "transport": "Transport",
  "volunteering": "Volunteering",
  "settings": "Settings",
  "sign-out": "Sign out",
  "log-in": "Log in",
  "reset-password": "Reset password",
  "send-report": "SEND REPORT",
  "name-surname": "Name and surname",
  "institution": "Institution",
  "category": "Category",
  "subject": "Subject",
  "description": "Description",
  "phone-number": "Phone number",
  "email": "Email",
  "add-location": "Add current location",
  "images": "Images",
  "send": "SEND",
  "required-field": "This field is required. Please fill in the field.",
  "only-numbers-field": "This field should contain only numbers",
  "wrong-number-format": '''Wrong phone number format
      \nWe accept the following:
      \n+40213-564-864
      \n+40213.564.864
      \n+40213 564 864
      \n0213-564-864
      \n0712456789''',
  "minimum-50": "This field should contain more than 50 characters",
  "email-format": "Wrong email format!\ne.g aaa@bb.ccc",
  "close": "Close",
  "other": "Other",
  "uncollected-garbage": "Uncollected garbage",
  "infrastructure": "Infrastructure",
  "utilities-problems": "Utilities problems",
  "illegal-constructions": "Illegal constructions",
  "safety": "Safety",
  "air-quality-pollution": "Air quality and pollution",
  "radauti-city-hall": "Radauti city hall",
  "comunal-services": "Comunal services",
  "acet-radauti": "ACET Radauti",
  "suceava-county-council": "Suceava County Council",
  "suceava-environmental-guard": "Suceava Environmental Guard",
  "suceava-forest-guard": "Suceava Forest Guard",
  "ocolul-silvic-marginea": "Ocolul Silvic Marginea",
  "dsp-suceava": "DSP Suceava",
  "radautiul-civic-association": "Radautiul Civic Association",
  "lead": "Government",
  "lead-info": "Informations about mayor, deputy and secretary",
  "local-council": "Local council",
  'local-council-info': "See the members of our council",
  "local-council-meetings": "Local council meetings",
  "local-council-meetings-info": "Live meetings",
  "local-council-decisions": "Local council decisions",
  "local-council-decisions-info": "New and old decisions made by our council",
  "mayor": "Mayor",
  "primar": "Mayor",
  "additional-information": "Additional information",
  "wealth-declaration": "Wealth declaration",
  "declaration-interests": "Declaration of interests",
  "deputy": "Deputy",
  "viceprimar": "Deputy",
  "secretary": "Secretary",
  "secretar": "Secretary",
  "tel": "Phone",
  "email:": "Email: ",
  "local-councillor": "Local councillor",
  "consilier-local": "Local councillor",
  "order": "Order",
  "see-order": "See order",
  "open-link": "Open Link",
  "new-events": "New events",
  "old-events": "Past events",
  "start-date": "Start date",
  "end-date": "End date",
  "inconveniences": "Inconvenience",
  "inconveniences-info":
      "Contact details for information or complaints about water, sewerage or utility services",
  "local-authorities": "Local authorities",
  "local-authorities-info":
      "Contact details for the main local public authorities (town hall, hospital, police, etc.)",
  "local-institutions": "Local institutions",
  "local-institutions-info":
      "Contact details for the main civil protection institutions (consumer, child, animal, environmental, etc.",
  "servicii-comunale": "Comunal services",
  "acet": "ACET",
  "politia-locala": "Local police",
  "spitalul-municipal": "Hospital",
  "primarie": "City hall",
  "adăpostul-de-animale": "Animal shelter",
  "protectia-consumatorului": "Consumer protection",
  "protectia-copilului": "Child protection",
  "poliția-animalelor": "Animal police",
  "protectia-mediului": "Environmental protection",
  "garda-de-mediu-suceava": "Suceava Environmental Guard",
  "local-announces": "Local announces",
  "local-announces-info":
      "Announcements from major institutions\nAnnouncements from local services",
  "jobs": "Jobs",
  "jobs-info": "Jobs ads taken from www.eradauti.ro",
  "real-estate": "Real estate",
  "real-estate-info": "Real estate ads taken from www.eradauti.ro",
  "graphs": "Graphics",
  "centru-radauti": "Air quality in Radauti",
  "bună": "Good",
  "acceptabilă": "Acceptable",
  "moderată": "Moderate",
  "rea": "Bad",
  "foarte-rea": "Really bad",
  "extrem-de-rea": "Extremely bad",
  "direction": "Direction",
  "N": "N",
  "NNE": "NNE",
  "NE": "NE",
  "ENE": "ENE",
  "E": "E",
  "ESE": "ESE",
  "SE": "SE",
  "SSE": "SSE",
  "S": "S",
  "SSV": "SSW",
  "SV": "SW",
  "VSV": "WSW",
  "V": "W",
  "VNV": "WNW",
  "NV": "NW",
  "NNV": "NNW",
  "NbE": "NbE",
  "NEbN": "NEbN",
  "NEbE": "NEbE",
  "EbN": "EbN",
  "EbS": "EbS",
  "SEbS": "SEbS",
  "SbE": "SbE",
  "SbV": "SbW",
  "SVbV": "SWbW",
  "VbS": "WbS",
  "VbN": "WbN",
  "NVbV": "NWbW",
  "NVbN": "NWbN",
  "NbV": "NbW",
  "m-s": "m/s",
  "mBar": "mBar",
  "radauti-iesire-dornesti": "Radauti - Dornest Exit",
  "device-location?": "Where is the device installed?",
  "device-location":
      "The air quality monitoring device is installed in the center of Radauti Municipality, in Piata Garoafelor and measures the concentration of PM2.5, CO2, temperature and relative humidity. The Radauti Weather Station is the official one installed by the Romanian authorities. The station is located on Str. Stephen the Great, No. 132 and measures temperature, relative humidity, wind speed, wind direction and atmospheric pressure.",
  "what-is-pm25?": "What are the PM2.5 particles?",
  "what-is-pm25":
      "PM2.5 particles are particles with a diameter of less than 2.5 micrometers (about 100 times smaller than a human hair) produced by the burning process of different fuels such as Diesel, biomass, coal, waste, etc.\n\nBeing so small and easily penetrating the lungs, PM2.5 particles are the most dangerous to health, especially in the urban environment. It is estimated that annually, in the European Union, more than 400,000 people die prematurely due to exposure to a high concentration of PM2.5 particles.\n\nIn Romania, the estimated number reaches approximately 25,000. These particles are so small that they easily enter the respiratory system and circulatory system, causing heart or lung problems such as bronchial asthma.\n\nThe average annual maximum limit set by the European Union is 25 μg/m\u00B3 and in the US of 12 μg/m\u00B3. Values ​​above 25 μg/m\u00B3 will always be observed on the device, especially when there are thermal inversions.\n\n It is very important that the values do not increase very much and the exposure is not long-lasting.",
  "color-meaning?": "What does the background color mean?",
  "color-meaning-blue": "PM2.5 level is good (0 - 10 \u03BCg/m\u00B3)",
  "color-meaning-green": "PM2.5 level is acceptable (10 - 20 \u03BCg/m\u00B3)",
  "color-meaning-yellow": "PM2.5 level is moderate (20 - 25 \u03BCg/m\u00B3)",
  "color-meaning-pink": "PM2.5 level is bad (25 - 50 \u03BCg/m\u00B3)",
  "color-meaning-red": "PM2.5 level is really bad (50 - 75 \u03BCg/m\u00B3)",
  "color-meaning-red-dark":
      "PM2.5 level is extremely bad (75 - 800 \u03BCg/m\u00B3)",
  "what-does-the-law-say?": "What does the law say about air quality?",
  "what-does-the-law-say":
      "In Romania, the main law that provides substantial information on the subject of air quality is Law No. 104 of 2011. The colors and concentration scale in this application are aligned with Order no. 1,818 of October 2, 2020 and takes into account the provisions of art. 87 para. (2) from Law no. 104/2011 regarding the quality of the surrounding air, with the subsequent amendments pursuant to art. 57 para. (1), (4) and (5) of the Government Emergency Ordinance no. 57/2019 on the Administrative Code, with subsequent amendments and additions, and of art. 13 para. (4) from Government Decision no. 43/2020 on the organization and operation of the Ministry of Environment, Water and Forests",
  "where-to-find-more-info?": "Where can I find more informations?",
  "where-to-find-more-info":
      "The Rădăutiul Civic team has built a special page for a detailed description of air quality parameters (http://calitateaer.radautiulcivic.ro). The page contains graphs showing how the concentration of PM2.5, CO2, Relative Humidity, Wind Speed ​​and Direction, Temperature and Atmospheric Pressure evolve over time.",
  "pm-time": "PM2.5 vs Time",
  "co2-time": "CO2 vs Time",
  "pm-speed-time": "PM2.5 & Speed vs Time",
  "temperature-time": "Temperature vs Time",
  "wind": "Wind",
  "time": "Time",
  "wind-speed": "Wind speed",
  "legend": "Legend",
  "temperature": "Temperature",
  "selected-value": "Selected value",
  "selected-value-is": "Selected value is",
  "value-date": "At the date of",
  "cabbies": "Cabbies",
  "cabbies-description": "List of authorized taxi drivers from Radauti",
  "trains": "Trains",
  "trains-description": "List of trains passing through Radauti",
  "minibuses": "Minibuses",
  "minibuses-description": "List of minibuses on the Radauti-Suceava route",
  "departure": "Departure",
  "arrival": "Arrival",
  "select": "-  Select  -",
  "radautiul-civic": "Radautiul Civic",
  "radautiul-civic-phone": "Phone: 0741975076",
  "radautiul-civic-email": "Email: radautiulcivic@gmail.com",
  "radautiul-civic-site": "https://www.radautiulcivic.ro",
  "toast-master": "Toastmasters Radauti",
  "toast-master-phone": "Phone: 0740757280",
  "toast-master-email": "radautitm@gmail.com",
  "toast-master-site": "https://www.facebook.com/radautitoastmasters",
  "club-eco": "Club Eco Montan",
  "club-eco-phone": "Phone: 0746814430",
  "club-eco-email": "clubulecomontan@gmail.com",
  "club-eco-site": "https://www.facebook.com/ClubulEcoMontanBucovinaRadauti",
  "bafi": "BAFI",
  "bafi-phone": "Phone: 0755403224",
  "bafi-email": "asociatia@bafi.ro",
  "bafi-site": "http://www.bafi.ro",
  "door-to-home": "Door to Home Association",
  "door-to-home-phone": "Phone: 0230562751",
  "door-to-home-email": "info@doortohome.ro",
  "door-to-home-site": "http://doortohome.ro",
  "maria-ward": "Maria Ward Association",
  "maria-ward-phone": "Phone: 0757114181",
  "maria-ward-email": "centrul.mariaward@gmail.com",
  "maria-ward-site": "https://centrulsocialmariaward.org",
  "umania": "Umania Association",
  "umania-email": "ioanadeliar@gmail.com",
  "umania-site": "https://www.facebook.com/umania.ffs",
  "about-us": "About Us",
  "privacy": "Privacy",
  "partners": "Partners",
  "privacy-terms": "Privacy terms",
  "contact-us": "Contact us",
  "about-app": "About this app",
  "no-results-found": "No results found",
  "please-retry": "Please try again",
  "about-us-app-description": 'The e-Rădăuți application is a voluntary project born in 2017 from the desire to bring the city closer to the digital age, to facilitate the involvement of local residents in local actions.'
      '\nThe application was born as a result of a first competition in the city entitled Let\'s digitize the city in which eighteen students from two high schools in Rădăuți participated.'
      '\nThe applications developed during the contest were evaluated by an international jury of IT and Design professionals and the financial resources for the awards came from donations from the members of the Rădăuțiul Civic, the jury and the local firm Hard Power Services.'
      '\nThe new version of the e-Rădăuți application is being implemented in 2020 with the help of funds obtained from the Geeks for Democracy association, through the Democracy Fund, and is dedicated only to local residents, temporarily abandoning the part dedicated to tourists.'
      '\nThis version was also updated with the support provided by Code4Romania, during the Civic Tech 911 technical sessions'
      '\nThis upgrade came with new functionalities but also with improvements to the already existing functionalities, the application being available for the first time also on iOS, not only on Android.'
      '\nThe application is the result of the work of a team formed by Ciprian Dicu, Luis Scripcaru, Paul Coman - on the development, code and algorithms side, Viviana Huțuleac and Daniela Tiron on the communication and graphics side and Luca Ciubotaru on the project management side.',
  "about-us-content-description": '\nThe Rădăutiul civic initiative group officially appeared in June 2017, after a series of civic actions'
      'already implemented by some members, on a voluntary basis and out of a desire to give something back to their hometown,'
      'and in September 2018 it became a non-governmental association.'
      '\nThe vision of the association "Rădăuțiul Civic" is that of a developed Rădăuţi, with a civil society'
      'strong, with responsible, educated, informed and active citizens who promote the good of the community.'
      '\nThe mission of the "Rădăuțiul Civic" association is to stimulate active citizenship for development '
      'local community.'
      '\nOur civic group\'s core values include:'
      '\n- the integrity and honesty of members and the community;'
      '\n- professionalism - we rely on quality actions, not for the image but for a real impact in the community;'
      '\n- responsibility - we are and we take responsibility for our actions. Only by assuming can we produce a change for the better around us;'
      '\n- transparency and truth in our actions and objectives;'
      '\n- non partisan - like any civic initiative, this group is not and will not be politically partisan;'
      '\n- devotion and courage are also among our values.'
      '\nWe like people with ideas, active people, people who DO and not just say. We like people who'
      "offers solutions, not just criticizes, and we like people who believe that through the power of example they can set"
      'things in motion.'
      '\nWe are citizens every day, not only when we go to vote every 4 years or when we have any '
      'problem. If we want a city that flourishes and develops, this also depends on '
      'us and what we do every day for it. A functioning democracy cannot exist by '
      'simply participating in the vote, but by assuming the status of a citizen every day.'
      '\nhttps://www.radautiulcivic.ro/',
  "contact-us-description":
      "If you have questions or suggestions regarding our privacy terms, do not hesitate to contact us at radautiulcivic@gmail.com. You can also request us to delete your personal data from our database at this email address.",
  "changes-privacy": "Changes to the privacy policy",
  "changes-privacy-description":
      "Whenever necessary, we may update our privacy policy. Consequently, we advise you to return to this page periodically in case some changes occur. You will receive notifications when there are changes to our privacy policy. These changes are effective as soon as they are posted on this page.",
  "child-privacy": "Children's privacy",
  "child-privacy-description":
      "These services are not intended for persons under the age of 13. We do not knowingly collect personally identifiable information from children under 13. If we discover that a child under 13 has provided us with personal information, we will immediately delete it from our servers. If you are a parent or guardian, or if you are aware that we have been provided with personal information from your child, please contact us as soon as possible so that we can take the necessary steps.",
  "security": "Security",
  "security-description":
      'We appreciate your trust when you provide us with personal information. That\'s why we try to use commercially acceptable means to protect it. However, you should note that no method of transmission over the Internet or electronic storage is 100% secure, and we cannot guarantee its absolute security.'
          '\nLinks to other sites or to other service providers'
          '\nThis application contains links and contact forms to other websites or service providers. If you click on a third-party link, you will be redirected to that site. Contact forms that are completed by the user for a third-party service will be sent directly to the third-party service provider. We remind you that we do not act with these external sites. Therefore, we recommend that you read the privacy policy of these sites. We have no control over, and assume no responsibility for, the content, privacy terms, or practices of any third party site or service.',
  "third-party-services": "Third party services",
  "third-party-services-description":
      "Most of the time, the data that is intended for third-party services will not be processed by \"Rădăutiul Civic\" but will be redirected to the service providers. \nWe want to inform app users that these third party services have access to personal information. The reason we might do this is to carry out certain tasks on our behalf. However, they are required not to disclose or use the information for other purposes.",
  "service-providers": "Service providers",
  "service-providers-description":
      "We may employ third-party companies and individuals for the following reasons:\n- to facilitate our own service\n- to provide users with third-party services (e.g. recycling)\n- to provide the service on our behalf\n- to perform services related to our service\n n- to be assisted to analyze how our service is used",
  "cookies": "Cookies",
  "cookies-description":
      "Cookies are files that contain small amounts of data that are used as a unique anonymous identifier. They are sent to the browser from the website you visit and are stored in the internal memory of the device. This service does not use cookies explicitly. However, the application may use third-party code and bookstores that use cookies to collect information and improve their services. You have the option to both accept and refuse these cookies and more, know when cookies are sent to your device. If you refuse to use them, you will only be able to use certain parts of the services.",
  "google-play-services": "Google Play services",
  "google-play-services-description":
      "We inform you that every time you use the application, information and data from the phone are collected by third-party products and transmitted in case of errors in log data. Log data may contain information such as your Internet Protocol (\"IP\") address, device name, operating system version, application configuration when you use our tools, date and time of application use, and other statistical data.",
  "collection-use": "Collection and use of information",
  "collection-use-description":
      "When you use our application, you will need to give us permission to use, among others, certain information related to your personal identity such as your phone or tablet camera, but also your GPS position.\nThe application uses third-party services that may collect information used to identify you. \nLinks to privacy terms used by the app:",
  "privacy-terms-description":
      'The independent group "Rădăuțiul civic" voluntarily built the "e-Rădăuți" application. The application is provided free of charge and should be used as such.'
          '\nThe application is a mobile tool to facilitate communication between local residents, local institutions and the "Rădăuțiul Civic" group. The role of communication is civic involvement or reporting on various problems encountered in society. Depending on the option accessed, the information that the user will enter in the various forms will be directed to our email address provided by the Google Mail service: radautiulcivic@gmail.com or to local institutions such as Rădăuți City Hall, Communal Services, ACET Rădăuți , Suceava County Council, Suceava Environmental Guard, Suceava Forest Guard, etc. When the data is sent to "Rădăuțiul Civic", it will be stored on the server of the e-mail address, therefore we recommend visiting the privacy policy of Google Inc (https://policies.google.com/privacy). When sent to public institutions, they will be stored on dedicated servers, without being processed or stored by "Rădăutiul Civic". We recommend contacting agencies regarding data storage.'
          '\nIf you choose to use our application you agree that we will collect and use information related to these terms. The personal information collected will be used when submitting requests or complaints to "Rădăutiul Civic". Options such as Report a problem send personal data (first and last name, email address, phone number and location) to the email address radautiulcivic@gmail.com (when sent to "Rădăutiul Civic") to which they have access members of the "Rădăuțiul Civic" group or to relatiipublice@primariaradauti.ro, office@serviciicomunale.ro, agentia.radauti@acetsv.ro, contact@cjsuceava.ro,cjsuceava@gnm.ro, gardaforestiera.suceava@gmail.com for public agencies to which different public persons employed at the respective agencies will have access.\nThe option to contact the persons in charge (Mayor, Deputy Mayor, Secretary or Councilors) will be made using the e-mail address of the selected person, using the telephone number or the address by Facebook. The data sent to each person in management will be stored and processed by them, which means that "Civic Shed" has no control over how it is used. To find out how they are processed, we recommend that you contact each one privately.'
          '\nRădăuțiul Civic is committed to protecting the personal data provided by the people or companies it collaborates with. To ensure that your personal data is safe, we regularly communicate the personal data protection policy as well as the work instructions related to this aspect to all users of the application and follow the strict application of privacy protection measures within the organization.'
          '\nThis privacy policy describes our practices regarding the collection, use and transfer of data communicated directly or indirectly to our organization, and how we use personal data for the purpose of providing services.'
          '\nIf, for any reason, the terms set out in these terms of use of personal data are not acceptable to you, you have the opportunity to communicate this to us and possibly request details or explicitly, the deletion of your data, by sending the message to the address mentioned in the preamble (radautiulcivic@gmail.com).'
          '\nInformation will not be shared publicly and will not be published except as specified in the "privacy terms".',
  "error": "Error",
  "update-password": "Change password",
  "new-password": "New password",
  "current-password": "Current password",
  "re-type-password": "Re-type new password",
  "public-announcements": "Public announcements",
  "map-title": "Map of reports from Radauti",
  "guest": "Use the app now with Guest status",
  "report-sent":
      "The report has been sent successfully\nYou will be notified by email in the following days",
  "permissions-text":
      "To be able to enjoy all the functionalities of e-Rădăuți, the application needs the following permissions, which we ask you to activate\nThese permissions can be changed later in the settings.",
  "forgot-password": "I forgot the password",
  "or-log-in-as": "Or log in as",
  "send-mail": "Send email",
  "new-password-match": "The password doesn't match",
  "create-new-account": "Create a new account",
  "password": "Password",
  "success": "Success",
  "success-sign-in": "You have been authenticated successfully",
  "user-created": "The user @name has been created",
  "reset-password-email": "An email has been sent to @email",
  "success-name-update": "You have successfully setted the name to: @name",
  "display-name": "Enter new name",
  "update-name": "Update name",
  "display-phone-number": "Enter new phone number",
  "update-phone-number": "Update phone number",
  "success-phone-update":
      "You have successfully setted the phone number to: @phone",
  "no-data-account": 'No name or phone number found for this account'
      '\nPlease update them using the field below',
  "couldnt-open-link": "We couldn't open this link please try again",
  "redirected-eradauti": "You will be redirected to www.eradauti.ro",
  "cancel": "Cancel",
  "yes": "Yes",
  "no": "No",
  "all": "All",
  "proceed": "Do you want to proceed?",
  "next": "Next",
  "back": "Back",
  'author': 'Author',
  'pm': "@value PM2.5 μg/m³",
  'co': '@value CO2',
  'wind-spd': "@value m/s",
  'pm-wind-time': "PM2.5 vs Wind vs Time",
  'hm-temp-time': "Humidity vs Temperature vs Time",
  'celsius': '@value °C',
  'hm': 'Humidity',
};
