Map<String, String> roRO = {
  'e-radauti': 'e-Rădăuți',
  'app-radauti': 'Aplicația e-Rădăuți',
  'home': 'Acasă',
  'developed-by':
      'Aplicație dezvoltată prin efortul Asociației Rădăuțiul Civic',
  'welcome': 'Bine ai venit!',
  'weak-password': 'Parola este slabă. Vă rugăm să furnizați o parolă mai bună',
  'user-not-found': 'Nu am putut crea un cont cu informațiile primite',
  'invalid-email': 'E-mailul este invalid',
  'user-disabled': 'Contul este dezactivat',
  'email-already-in-use': 'Există deja un cont cu acest e-mail',
  'invalid-credential': 'Datele sunt invalide sau au expirat',
  'wrong-password': 'Parola este greșită',
  'invalid-verification-code': 'Codul de verificare este invalid',
  'invalid-verification-id': 'ID-ul de este invalid',
  'password-mismatch': 'Vechea parolă nu se potrivește',
  'user-mismatch': 'Informațiile introduse nu corespund utilizatorului curent',
  'expired-action-code': 'Codul a expirat',
  'my-account': 'Contul meu',
  'report-problem': 'Raportează o problemă',
  'local-administration': 'Administrație locală',
  'events': 'Evenimente',
  'usefull-info': 'Informații utile',
  'usefull-numbers': 'Numere de telefon utile',
  'announces': 'Anunțuri',
  ' -quality': 'Calitatea aerului',
  'transport': 'Transport',
  'volunteering': 'Voluntariat',
  'settings': 'Setări',
  'sign-out': 'Deconectează-te',
  'log-in': 'Intră în cont',
  'reset-password': 'Resetează parola',
  'send-report': 'TRIMITE SESIZARE',
  'name-surname': 'Numele și prenumele',
  'username': 'Nume de utilizator\n@name',
  'institution': 'Instituţie',
  'category': 'Categorie',
  'subject': 'Subiect',
  'description': 'Descriere',
  'phone-number': 'Număr de telefon',
  'email': 'Email',
  "email-value": "Email: @email",
  'add-location': 'Adăugați locația curentă',
  'images': 'Imagini',
  'send': 'TRIMITE',
  'required-field': 'Acest căsuță este obligatorie. Vă rugăm să o completați.',
  'only-numbers-field': 'Acest câmp trebuie să conțină numai numere',
  'wrong-number-format':
      'Format greșit al numărului de telefon\n   \nAcceptăm următoarele:\n   \n+40213-564-864\n   \n+40213.564.864\n   \n+40213 564 864\n   \n0213-564-864\n   \n0712456789',
  'minimum-50': 'Această căsuță trebuie să conțină mai mult de 50 de caractere',
  'email-format': 'Format de e-mail greșit!\nde ex. aaa@bb.ccc',
  'close': 'Închide',
  'other': 'Altele',
  'uncollected-garbage': 'Gunoi neridicat',
  'infrastructure': 'Infrastructură',
  'utilities-problems': 'Probleme cu utilitățile',
  'illegal-constructions': 'Construcții ilegale',
  'safety': 'Siguranță',
  'infrastructure-streets': "Infrastructură (străzi, trotuare)",
  'air-quality': 'Calitatea aerului',
  'air-quality-pollution': 'Calitatea aerului și poluarea',
  'radauti-city-hall': 'Primăria Radauti',
  'comunal-services': 'Servicii Comunale',
  'acet-radauti': 'ACET Rădăuți',
  'suceava-county-council': 'Consiliul Județean Suceava',
  'suceava-environmental-guard': 'Garda de Mediu Suceava',
  'suceava-forest-guard': 'Garda Forestieră Suceava',
  'ocolul-silvic-marginea': 'Ocolul Silvic Marginea',
  'dsp-suceava': 'DSP Suceava',
  'radautiul-civic-association': 'Asociația Rădăuțiul Civic',
  'lead': 'Conducere',
  'lead-info': 'Informații despre primar, viceprimar și secretarul general',
  'local-council': 'Consiliul Local',
  'local-council-info':
      'Vezi detalii despre consilierii locali și datele lor de contact',
  'local-council-meetings': 'Ședințe de Consiliu Local',
  'local-council-meetings-info': 'Vezi ședințele de Consiliu Local',
  'local-council-decisions': 'Hotărârile Consiliului Local',
  'local-council-decisions-info': 'Hotărârile luate de Consiliul Local',
  'mayor': 'Primar',
  'primar': 'Primar',
  'additional-information': 'Informații suplimentare',
  'wealth-declaration': 'Declarația de avere',
  'declaration-interests': 'Declarația de interese',
  'deputy': 'Adjunct',
  'viceprimar': 'Adjunct',
  'secretary': 'Secretar',
  'secretar': 'Secretar',
  'tel': 'Telefon',
  'email:': 'E-mail:',
  'local-councillor': 'Consilier Local',
  "consilier-local": "Consilier Local",
  'order': 'Ședința din data de',
  'see-order': 'Vezi ordinea',
  'open-link': 'Deschide link-ul',
  'new-events': 'Evenimente noi',
  'old-events': 'Evenimente trecute',
  'start-date': 'Data de început',
  'end-date': 'Data de încheiere',
  'inconveniences': 'Deranjamente',
  'inconveniences-info':
      'Date de contact pentru informații sau reclamații despre servicii de apă, canalizare sau utilități.',
  'local-authorities': 'Autoritățile locale',
  'local-authorities-info':
      'Date de contact ale principalelor autorități publice locale (Primărie, spital, poliție etc.).',
  'local-institutions': 'Instituțiile locale',
  'local-institutions-info':
      'Date de contact pentru principalele instituții de protecție civilă (consumator, copil, animal, mediu etc.',
  'servicii-comunale': 'Servicii Comunale',
  'acet': 'ACET',
  'politia-locala': 'Poliția locală',
  'spitalul-municipal': 'Spital',
  'primarie': 'Primărie',
  'adăpostul-de-animale': 'Adăpostul de animale',
  'protectia-consumatorului': 'Protecția Consumatorului',
  'protectia-copilului': 'Protecția Copilului',
  'poliția-animalelor': 'Poliția animalelor',
  'protectia-mediului': 'Protecția mediului',
  'garda-de-mediu-suceava': 'Garda de Mediu',
  'local-announces': 'Anunțuri locale',
  'local-announces-info':
      'Anunțuri de la instituții\nAnunțuri de la serviciile locale',
  'jobs': 'Locuri de muncă',
  'jobs-info': 'Anunțuri de locuri de muncă preluate de pe www.eradauti.ro',
  'real-estate': 'Imobiliare',
  'real-estate-info': 'Anunțuri imobiliare preluate de pe www.eradauti.ro',
  'graphs': 'Grafice',
  'centru-radauti': 'Calitatea aerului în Rădăuți',
  'bună': 'Bună',
  'acceptabilă': 'Acceptabilă',
  'moderată': 'Moderată',
  'rea': 'Rea',
  'foarte-rea': 'Foarte rea',
  'extrem-de-rea': 'Extrem de rea',
  'direction': 'Direcţie',
  'N': 'N',
  'NNE': 'NNE',
  'NE': 'NE',
  'ENE': 'ENE',
  'E': 'E',
  'ESE': 'ESE',
  'SE': 'SE',
  'SSE': 'SSE',
  'S': 'S',
  'SSV': 'SSV',
  'SV': 'SV',
  'VSV': 'VSV',
  'V': 'V',
  'VNV': 'VNV',
  'NV': 'NV',
  'NNV': 'NNV',
  'NbE': 'NbE',
  'NEbN': 'NEbN',
  'NEbE': 'NEbE',
  'EbN': 'EbN',
  'EbS': 'EbS',
  'SEbS': 'SEbS',
  'SbE': 'SbE',
  'SbV': 'SbV',
  'SVbV': 'SVbV',
  'VbS': 'VbS',
  'VbN': 'VbN',
  'NVbV': 'NVbV',
  'NVbN': 'NVbN',
  'NbV': 'NbV',
  'm-s': 'm/s',
  'mBar': 'mBar',
  'radauti-center': 'Rădăuți - centru',
  'radauti-iesire-dornesti': 'Rădăuți - Ieșire Dornești',
  'device-location?': 'Unde este instalat dispozitivul?',
  'device-location':
      'Aparatul de monitorizare a calității aerului este instalat în centrul Municipiului Rădăuți, în Piața Garoafelor și măsoară concentrația de PM2.5, CO2, temperatura și umiditatea relativă. Stația Meteo Rădăuți este cea oficială, instalată de autoritățile române. Stația este situată pe Str. Ştefan cel Mare, nr. 132 şi măsoară temperatura, umiditatea relativă, viteza vântului, direcţia vântului şi presiunea atmosferică.',
  'what-is-pm25?': 'Ce sunt particulele PM2.5?',
  'what-is-pm25':
      'Particulele PM2,5 sunt particule cu un diametru mai mic de 2,5 micrometri (de aproximativ 100 de ori mai mic decât un păr uman) produse prin procesul de ardere a diferiților combustibili precum motorina, biomasa, cărbunele, deșeurile etc.\n\nFiind atât de mici și pătrunzând ușor în plămâni, particulele de PM2,5 sunt cele mai periculoase pentru sănătate, în special în mediul urban. Se estimează că anual, în Uniunea Europeană, peste 400.000 de oameni mor prematur din cauza expunerii la o concentrație mare de particule PM2,5.\n\nÎn România, numărul estimat ajunge la aproximativ 25.000. Aceste particule sunt atât de mici încât intră cu ușurință în sistemul respirator și sistemul circulator, provocând probleme cardiace sau pulmonare, cum ar fi astmul bronșic.\n\nLimita maximă medie anuală stabilită de Uniunea Europeană este de 25 μg/m³ și în SUA de 12 μg/m³. Valorile de peste 25 μg/m³ vor fi întotdeauna observate pe dispozitiv, mai ales când există inversiuni termice.\n\nEste foarte important ca valorile să nu crească foarte mult și expunerea să nu fie de lungă durată.',
  'color-meaning?': 'Ce înseamnă culoarea de fundal?',
  'color-meaning-blue': 'Nivelul PM2.5 este bun (0 - 10 μg/m³)',
  'color-meaning-green': 'Nivelul PM2,5 este acceptabil (10 - 20 μg/m³)',
  'color-meaning-yellow': 'Nivelul PM2.5 este moderat (20 - 25 μg/m³)',
  'color-meaning-pink': 'Nivelul PM2.5 este rău (25 - 50 μg/m³)',
  'color-meaning-red': 'Nivelul PM2.5 este foarte rău (50 - 75 μg/m³)',
  'color-meaning-red-dark': 'Nivelul PM2.5 este extrem de rău (75 - 800 μg/m³)',
  'what-does-the-law-say?': 'Ce spune legea despre calitatea aerului?',
  'what-does-the-law-say':
      'În România, principala lege care oferă informații substanțiale pe tema calității aerului este Legea nr. 104 din 2011. Culorile și scara de concentrație din această cerere sunt aliniate cu Ordinul nr. 1.818 din 2 octombrie 2020 și are în vedere prevederile art. 87 alin. (2) din Legea nr. 104/2011 privind calitatea aerului înconjurător, cu modificările ulterioare în temeiul art. 57 alin. (1), (4) și (5) din Ordonanța de urgență a Guvernului nr. 57/2019 privind Codul administrativ, cu modificările și completările ulterioare, și ale art. 13 alin. (4) din Hotărârea Guvernului nr. 43/2020 privind organizarea și funcționarea Ministerului Mediului, Apelor și Pădurilor.',
  'where-to-find-more-info?': 'Unde pot găsi mai multe informații?',
  'where-to-find-more-info':
      'Echipa Rădăuțiul Civic a construit o pagină specială pentru o descriere detaliată a parametrilor de calitate a aerului (http://calitateaer.radautiulcivic.ro). Pagina conține grafice care arată cum evoluează în timp concentrația de PM2,5, CO2, umiditatea relativă, viteza și direcția vântului, temperatura și presiunea atmosferică.',
  'pm-time': 'PM2.5 vs. timp',
  'co2-time': 'CO2 vs. timp',
  'pm-speed-time': 'PM2.5 și viteza vântului',
  'temperature-time': 'Temperatură vs timp',
  'wind': 'Vânt',
  'time': 'Timp',
  'wind-speed': 'Viteza vântului',
  'legend': 'Legendă',
  'temperature': 'Temperatura',
  'selected-value': 'Valoarea selectată',
  'selected-value-is': 'Valoarea selectată este',
  'value-date': 'La data de',
  'cabbies': 'Taximetrişti',
  'cabbies-description': 'Lista taximetriștilor autorizați din Rădăuți',
  'trains': 'Trenuri',
  'trains-description': 'Lista trenurilor care trec prin Rădăuți',
  "radautiul-civic": "Rădăuțiul Civic",
  "radautiul-civic-phone": "Phone: 0741975076",
  "radautiul-civic-email": "radautiulcivic@gmail.com",
  "radautiul-civic-site": "https://www.radautiulcivic.ro",
  "toast-master": "Toastmasters Rădăuți",
  "toast-master-phone": "Phone: 0740757280",
  "toast-master-email": "radautitm@gmail.com",
  "toast-master-site": "https://www.facebook.com/radautitoastmasters",
  "club-eco": "Clubul Eco Montan",
  "club-eco-phone": "Phone: 0746814430",
  "club-eco-email": "clubulecomontan@gmail.com",
  "club-eco-site": "https://www.facebook.com/ClubulEcoMontanBucovinaRadauti",
  "bafi": "BAFI",
  "bafi-phone": "Phone: 0755403224",
  "bafi-email": "asociatia@bafi.ro",
  "bafi-site": "http://www.bafi.ro",
  "door-to-home": "Asociația Door to Home",
  "door-to-home-phone": "Phone: 0230562751",
  "door-to-home-email": "info@doortohome.ro",
  "door-to-home-site": "http://doortohome.ro",
  "maria-ward": "Asociația Maria Ward",
  "maria-ward-phone": "Phone: 0757114181",
  "maria-ward-email": "centrul.mariaward@gmail.com",
  "maria-ward-site": "https://centrulsocialmariaward.org",
  "umania": "Asociația Umania",
  "umania-email": "ioanadeliar@gmail.com",
  "umania-site": "https://www.facebook.com/umania.ffs",
  'about-us': 'Despre noi',
  'privacy': 'Confidențialitate',
  'partners': 'Parteneri',
  'privacy-terms': 'Termeni și Condiții',
  'contact-us': 'Contactează-ne',
  'about-app': 'Despre această aplicație',
  'no-results-found': 'Nici un rezultat găsit',
  'please-retry': 'Vă rugăm să încercați din nou',
  'about-us-app-description':
      'Aplicația e-Rădăuți este un proiect voluntar născut în 2017 din dorința de a apropia orașul de era digitală, de a facilita implicarea localnicilor în acțiuni locale.\nAplicația a luat naștere în urma unui prim concurs din oraș intitulat ,,Să digitizăm orașul” la care au participat optsprezece elevi de la două licee din Rădăuți.\nAplicațiile dezvoltate în cadrul concursului au fost evaluate de un juriu internațional format din profesioniști în IT și Design, iar resursele financiare pentru premii au provenit din donații de la membrii Asociației Rădăuțiul Civic, juriul și firma locală Hard Power Services.\nNoua versiune a aplicației e-Rădăuți este implementată în 2020 cu ajutorul fondurilor obținute de la asociația Geeks for Democracy, prin Fondul Democrație, și este dedicată doar localnicilor..\nAceastă versiune a fost actualizată și cu suportul oferit de Code4Romania, în cadrul sesiunilor tehnice Civic Tech 911\nAcest upgrade a venit cu funcționalități noi, dar și cu îmbunătățiri la funcționalitățile deja existente, aplicația fiind disponibilă pentru prima dată și pe iOS, nu doar pe Android.\nAplicația este rezultatul muncii unei echipe formate din Ciprian Dicu, Luis Scripcaru, Paul Coman - pe partea de dezvoltare, cod și algoritmi, Viviana Huțuleac și Daniela Tiron pe partea de comunicare și grafică și Luca Ciubotaru pe partea de management de proiect. .',
  'about-us-content-description':
      'Grupul de inițiativă civică Rădăuțiul Civic a apărut oficial în iunie 2017, după o serie de acțiuni civice deja implementate de unii membri, pe bază de voluntariat și din dorința de a da ceva înapoi orașului natal, iar în septembrie 2018 a devenit asociație neguvernamentală. .\nViziunea asociației este aceea a unui Rădăuți dezvoltat, cu o societate civilă puternică, cu cetățeni responsabili, educați, informați și activi, care promovează binele comunității.\nMisiunea Asociației Rădăuțiul Civic este de a stimula cetățenia activă pentru dezvoltarea comunității locale.\nValorile de bază ale grupului nostru civic includ:\n- integritatea și onestitatea membrilor și a comunității;\n- profesionalism - ne bazăm pe acțiuni de calitate, nu pentru imagine, ci pentru un impact real în comunitate;\n- responsabilitate - suntem și ne asumăm responsabilitatea pentru acțiunile noastre;\n- transparență și adevăr în acțiunile și obiectivele noastre;\n- non-partizan - ca orice inițiativă civică, acest grup nu este și nu va fi partizan politic;\n- devotamentul și curajul sunt și ele printre valorile noastre.\nNe plac oamenii cu idei, oamenii activi, oamenii care FAC și nu doar spun. Ne plac oamenii care oferă soluții, nu doar critică și ne plac oamenii care cred că prin puterea exemplului pot pune lucrurile în mișcare.\n O democrație funcțională nu poate exista prin simpla participare la vot, ci prin asumarea statutului de cetățean în fiecare zi.\nhttps://www.radautiulcivic.ro/',
  'contact-us-description':
      'Dacă aveți întrebări sau sugestii cu privire la termenii noștri de confidențialitate, nu ezitați să ne contactați la radautiulcivic@gmail.com. De asemenea, ne puteți solicita să ștergem datele dumneavoastră cu caracter personal din baza noastră de date la această adresă de e-mail.',
  'changes-privacy': 'Modificări ale politicii de confidențialitate',
  'changes-privacy-description':
      'Ori de câte ori este necesar, putem actualiza politica noastră de confidențialitate. În consecință, vă sfătuim să reveniți periodic pe această pagină în cazul în care apar unele modificări. Veți primi notificări când există modificări ale politicii noastre de confidențialitate. Aceste modificări sunt efective de îndată ce sunt postate pe această pagină.',
  'child-privacy': 'Intimitatea copiilor',
  'child-privacy-description':
      'Această aplicație nu este destinată persoanelor sub 13 ani. Nu colectăm cu bună știință informații de identificare personală de la copiii sub 13 ani. Dacă descoperim că un copil sub 13 ani ne-a furnizat informații personale, le vom șterge imediat de pe serverele noastre. Dacă sunteți părinte sau tutore sau dacă știți că ni s-au furnizat informații personale de la copilul dumneavoastră, vă rugăm să ne contactați cât mai curând posibil pentru a putea lua măsurile necesare.',
  'security': 'Securitate',
  'security-description':
      'Apreciem încrederea dumneavoastră atunci când ne furnizați informații personale. De aceea încercăm să folosim mijloace acceptabile din punct de vedere comercial pentru a-l proteja. Cu toate acestea, trebuie să rețineți că nicio metodă de transmitere prin Internet sau stocare electronică nu este 100% sigură și nu putem garanta securitatea absolută a acesteia.\nLink-uri către alte site-uri sau către alți furnizori de servicii\nAceastă aplicație conține link-uri și formulare de contact către alte site-uri web sau furnizori de servicii. Dacă faceți clic pe un link terță parte, veți fi redirecționat către acel site. Formularele de contact care sunt completate de utilizator pentru un serviciu terță parte vor fi trimise direct furnizorului de servicii terță parte. Vă reamintim că nu acționăm cu aceste site-uri externe. Prin urmare, vă recomandăm să citiți politica de confidențialitate a acestor site-uri. Nu avem control asupra conținutului, termenii de confidențialitate sau practicile oricărui site sau serviciu terță parte și nu ne asumăm nicio responsabilitate pentru acesta.',
  'third-party-services': 'Servicii ale terților',
  'third-party-services-description':
      'De cele mai multe ori, datele care sunt destinate serviciilor terților nu vor fi prelucrate de Rădăutiul Civic, ci vor fi redirecționate către furnizorii de servicii.\nDorim să informăm utilizatorii aplicației că aceste servicii terțe au acces la informații personale. Motivul pentru care am putea face acest lucru este să îndeplinim anumite sarcini în numele nostru. Cu toate acestea, li se cere să nu dezvăluie sau să utilizeze informațiile în alte scopuri.',
  'service-providers': 'Prestatori de servicii',
  'service-providers-description':
      'Putem angaja companii și persoane terțe din următoarele motive:\n- pentru a ne facilita propriul serviciu\n- pentru a oferi utilizatorilor servicii terțe (de exemplu, reciclare)\n- pentru a furniza serviciul în numele nostru\n- pentru a presta servicii legate de serviciul nostru\n n- să fim asistați să analizăm modul în care este utilizat serviciul nostru',
  'cookies': 'Cookie-uri',
  'cookies-description':
      'Cookie-urile sunt fișiere care conțin cantități mici de date care sunt utilizate ca un identificator unic anonim. Acestea sunt trimise browserului de pe site-ul pe care îl vizitați și sunt stocate în memoria internă a dispozitivului. Acest serviciu nu folosește cookie-uri în mod explicit. Cu toate acestea, aplicația poate folosi coduri de la terți și librăriile care folosesc cookie-uri pentru a colecta informații și pentru a-și îmbunătăți serviciile. Aveți opțiunea de a accepta și de a refuza aceste cookie-uri și, mai mult, de a afla când sunt trimise cookie-uri pe dispozitivul dvs. Dacă refuzați să le utilizați, veți putea folosi doar anumite părți ale serviciilor.',
  'google-play-services': 'Servicii Google Play',
  'google-play-services-description':
      'Vă informăm că de fiecare dată când utilizați aplicația, informațiile și datele de pe telefon sunt colectate de produse terțe și transmise în cazul unor erori în datele de jurnal. Datele de jurnal pot conține informații precum adresa dvs. de protocol de Internet ("IP"), numele dispozitivului, versiunea sistemului de operare, configurația aplicației atunci când utilizați instrumentele noastre, data și ora de utilizare a aplicației și alte date statistice.',
  'collection-use': 'Colectarea și utilizarea informațiilor',
  'collection-use-description':
      'Când utilizați aplicația noastră, va trebui să ne dați permisiunea de a folosi, printre altele, anumite informații legate de identitatea dumneavoastră personală, cum ar fi camera telefonului sau tabletei, dar și poziția dumneavoastră GPS.\nAplicația utilizează servicii terțe care pot colecta informații utilizate pentru a vă identifica.\nLink-uri către termenii de confidențialitate utilizați de aplicație:',
  'privacy-terms-description':
      'Grupul independent „Rădăuțiul civic” a construit în mod voluntar aplicația „e-Rădăuți”. Aplicația este oferită gratuit și trebuie utilizată ca atare.\nAplicația este un instrument mobil pentru a facilita comunicarea dintre localnici, instituțiile locale și Asociația Rădăuțiul Civic. Rolul comunicării este implicarea civică sau raportarea asupra diverselor probleme întâlnite în societate. În funcție de opțiunea accesată, informațiile pe care utilizatorul le va introduce în diferitele formulare vor fi direcționate către adresa noastră de e-mail furnizată de serviciul Google Mail: radautiulcivic@gmail.com sau către instituții locale precum Primăria Rădăuți, Servicii Comunale, ACET. Rădăuți , Consiliul Județean Suceava, Garda de Mediu Suceava, Garda Forestieră Suceava etc. Când datele sunt trimise către Rădăuțiul Civic, acestea vor fi stocate pe serverul adresei de e-mail, de aceea vă recomandăm să vizitați politica de confidențialitate a Google Inc (https://policies.google.com/privacy). Atunci când sunt trimise către instituțiile publice, acestea vor fi stocate pe servere dedicate, fără a fi prelucrate sau stocate de Asociația Rădăuțiul Civic. Vă recomandăm să contactați agențiile cu privire la stocarea datelor.\nDacă alegeți să utilizați aplicația noastră, sunteți de acord că vom colecta și folosi informații legate de acești termeni. Informațiile personale colectate vor fi folosite la depunerea cererilor sau reclamațiilor către Rădăutiul Civic. Opțiuni precum Raportarea unei probleme trimit date personale (nume și prenume, adresa de e-mail, număr de telefon și locație) la adresa de e-mail radautiulcivic@gmail.com (când sunt trimise la „Rădăutiul Civic”) la care au acces membrii asociației Rădăuțiul Civic sau la relatiipublice@primariaradauti.ro, office@serviciicomunale.ro, agentia.radauti@acetsv.ro, contact@cjsuceava.ro,cjsuceava@gnm.ro, gardaforestiera.suceava@gmail.com pentru agențiile publice la care vor avea acces diferite persoane publice angajate la agentiile respective.\nOpțiunea de a contacta responsabilii (Primar, Viceprimar, Secretar sau Consilieri) se va face folosind adresa de e-mail a persoanei selectate, folosind numărul de telefon sau adresa de Facebook. Datele trimise fiecărei persoane din conducere vor fi stocate și prelucrate de către aceasta, ceea ce înseamnă că Asociația Rădăuțiul Civic nu are control asupra modului în care este utilizată. Pentru a afla cum sunt procesate, vă recomandăm să le contactați pe fiecare în privat.\nRădăuțiul Civic se angajează să protejeze datele personale furnizate de persoanele sau companiile cu care colaborează. Pentru a ne asigura că datele dumneavoastră cu caracter personal sunt în siguranță, comunicăm în mod regulat politica de protecție a datelor cu caracter personal precum și instrucțiunile de lucru legate de acest aspect tuturor utilizatorilor aplicației și urmăm aplicarea strictă a măsurilor de protecție a confidențialității în cadrul organizației.\nAceastă politică de confidențialitate descrie practicile noastre cu privire la colectarea, utilizarea și transferul datelor comunicate direct sau indirect organizației noastre și modul în care folosim datele personale în scopul furnizării de servicii.\nDacă, din orice motiv, condițiile expuse în acești termeni de utilizare a datelor cu caracter personal nu sunt acceptabile pentru dvs., aveți posibilitatea de a ne comunica acest lucru și, eventual, de a solicita detalii sau în mod explicit, ștergerea datelor dvs., prin trimiterea mesajului. la adresa menționată în preambul (radautiulcivic@gmail.com).\nInformațiile nu vor fi partajate public și nu vor fi publicate, cu excepția celor specificate în „termenii de confidențialitate”.',
  'error': 'Eroare',
  'update-password': 'Schimbaţi parola',
  'new-password': 'Parolă Nouă',
  'current-password': 'Parola actuală',
  're-type-password': 'Reintroduceți parola nouă',
  'public-announcements': 'Anunțuri publice',
  'map-title': 'Harta rapoartelor din Rădăuți',
  'guest': 'Continuă ca vizitator',
  'report-sent':
      'Raportul a fost trimis cu succes\nVeți fi anunțat prin e-mail în următoarele zile',
  'permissions-text':
      'Pentru a vă putea bucura de toate funcționalitățile e-Rădăuți, aplicația are nevoie de următoarele permisiuni, pe care vă rugăm să le activați\nAceste permisiuni pot fi modificate mai târziu în setări.',
  'forgot-password': 'Ai uitat parola?',
  'or-log-in-as': 'Sau conectați-vă ca',
  'send-mail': 'Trimite email',
  'new-password-match': 'Parola nu se potrivește',
  'create-new-account': 'Creează-ți cont',
  'password': 'Parolă',
  'success': 'Succes',
  'success-sign-in': 'Ați fost autentificat cu succes',
  'user-created': 'Utilizatorul @name a fost creat',
  'reset-password-email':
      'Un e-mail a fost trimis la @email pentru resetarea parolei',
  'success-name-update': 'Ați setat cu succes numele la: @name',
  'display-name': 'Introduceți un nume nou',
  'update-name': 'Actualizați numele',
  'display-phone-number': 'Introduceți un număr nou de telefon',
  'update-phone-number': 'Actualizați numărul de telefon',
  'success-phone-update': 'Ați setat cu succes numărul de telefon la: @phone',
  'no-data-account':
      'Nu a fost găsit niciun nume sau număr de telefon pentru acest cont\nVă rugăm să le actualizați folosind căsuța de mai jos',
  'couldnt-open-link':
      'Nu am putut deschide acest link, vă rugăm să încercați din nou',
  'redirected-eradauti': 'Veți fi redirecționat către www.eradauti.ro',
  'cancel': 'Anulare',
  'yes': 'Da',
  'no': 'Nu',
  'all': 'Toate',
  'proceed': 'Vrei să continui?',
  'next': 'Următorul',
  'back': 'Înapoi',
  'author': "Autor",
  'pm': "@value PM2.5 μg/m³",
  'co': '@value CO2',
  'wind-spd': "@value m/s",
  'wind-time': "PM2.5 vs Vânt vs Timp",
  'hm-temp-time': "Umiditate vs Temperatură vs Timp",
  'celsius': '°C',
  'hm': "Umiditate",
  'limit-pm': 'Limita legală de PM2,5',
  "sign-out-text": "Doriți să vă deconectați?",
  "email-address": "Adresă de email",
  "remember-me": "Ține-mă conectat",
  "register-account": "Vrei să te înregistrezi în aplicație? ",
  "or": "Sau",
};
