name: flutterapperadauti
description: A new Flutter application.

publish_to: "none"
version: 3.3.3

environment:
    sdk: ">=2.17.0 <5.0.0"

dependencies:
    auto_size_text: ^3.0.0
    cached_network_image: ^3.2.2
    card_loading: ^0.2.1
    cloud_firestore: ^4.2.0
    cupertino_icons: ^1.0.4
    custom_navigation_bar: ^0.8.2
    dio: ^4.0.6
    expandable: ^5.0.1
    firebase_auth: ^4.2.0
    firebase_core: ^2.4.0
    firebase_messaging: ^14.1.4
    firebase_storage: ^11.0.7
    flex_color_scheme: ^6.0.1
    flutter:
        sdk: flutter
    flutter_blurhash: ^0.7.0
    flutter_form_builder: ^7.1.1
    flutter_inappwebview: ^5.3.2
    flutter_loadingindicator: ^1.0.1
    flutter_local_notifications: ^9.4.0
    flutter_localization: ^0.1.9
    flutter_map: ^2.2.0
    flutter_map_marker_cluster: ^0.5.0
    flutter_speed_dial: ^6.0.0
    flutter_svg: ^1.0.3
    flutter_widget_from_html: ^0.8.5
    fluttericon: ^2.0.0
    form_builder_image_picker: ^3.1.0
    form_builder_validators: ^8.1.0
    geolocator: ^9.0.1
    get: ^4.6.5
    google_sign_in: ^5.4.2
    intl: ^0.17.0
    js: ^0.6.4
    json_annotation: ^4.7.0
    json_serializable: ^6.5.2
    location: any
    logger: ^1.1.0
    octo_image: ^1.0.2
    searchbar_animation: ^0.0.4
    selectable_autolink_text: ^2.3.0
    shared_preferences: ^2.0.15
    syncfusion_flutter_charts: ^20.1.48
    timeline_tile: ^2.0.0
    url_launcher: ^6.0.20

dev_dependencies:
    build_runner: ^2.3.1
    dependency_validator: ^3.0.0
    flutter_launcher_icons: ^0.9.3
    flutter_lints: ^2.0.1
    flutter_native_splash: ^2.1.6
    flutter_test:
        sdk: flutter

flutter_native_splash:
    image: assets/logo_images/prop_6.png
    color: "#ffffff"
    color_dark: "#ffffff"
    android: true
    ios: true
    web: false

flutter_icons:
    image_path_android: "assets/logo_images/app_logo_final.png"
    image_path_ios: "assets/logo_images/app_logo_final.png"
    android: true
    ios: true

flutter:
    assets:
        - assets/
        - assets/faces/
        - assets/buttons/
        - assets/images/
        - assets/images/volunteer/
        - assets/logo_images/
        - assets/images/
        - assets/wind/
    uses-material-design: true

flutter_assets:
    assets_path: assets/
    output_path: lib/utils/
    filename: assets.dart
