name: flutterapperadauti
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  add_2_calendar: ^2.1.1
  ai_awesome_message: ^2.0.0
  camera: ^0.9.4+1
  cloud_firestore: ^2.5.3
  cupertino_icons: ^1.0.0
  custom_info_window: ^1.0.1
  dio: ^4.0.0
  dio_http_cache: ^0.3.0
  expandable: ^4.1.4
  firebase_core: ^1.10.0
  firebase_database: ^6.0.0
  firebase_messaging: ^10.0.8
  flutter_form_builder: ^7.0.0
  flutter_icons: ^1.1.0
  flutter_linkify: ^4.1.0
  flutter_local_notifications: ^8.2.0
  flutter_map: ^0.14.0
  flutter_map_marker_popup: ^2.0.0
  flutter_paginator: ^0.0.6
  flutter_speed_dial: ^2.1.1
  flutter_svg: ^0.22.0
  flutter_widget_from_html: ^0.7.0
  fluttericon: ^1.0.7
  form_builder_image_picker: ^2.0.0
  gallery_saver: ^2.0.1
  geolocator: ^7.6.2
  get_it: ^5.0.6
  http: ^0.13.1
  infinite_scroll_pagination: ^2.3.0
  intl: ^0.17.0
  list_tile_switch: ^0.0.2
  overlay_support: ^1.0.5
  path_provider: ^2.0.5
  permission_handler: ^8.1.6
  provider: ^6.0.1
  
  timeline_tile: ^1.0.0
  url_launcher: ^6.0.12
  weather_icons: ^2.0.2
  intro_views_flutter: ^3.2.0
  is_first_run: ^1.0.0
  firebase_image: ^1.0.0
  firebase_storage: ^8.1.3
  flutter_autolink_text: ^1.0.0+1
  flutter_map_marker_cluster: ^0.4.3
  form_builder_validators: ^7.2.0
  flutter_inappwebview: ^5.3.2
  syncfusion_flutter_charts: ^19.4.38
  package_info_plus: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2   
  flutter_native_splash: ^1.3.2

flutter_native_splash:
  image: "assets/logo_images/prop_6.png" 
  color: "#ffffff"
  android: true
  ios: true

flutter_email_sender:
  path: ../

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
flutter_icons:
  #  image_path: "assets/images/icon-128x128.png"
  image_path_android: "assets/logo_images/app_logo_final.png"
  image_path_ios: "assets/logo_images/app_logo_final.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
# The following section is specific to Flutter.
flutter:
  assets:
    - assets/
    - assets/images/
    - assets/logo_images/
    - assets/images/volunteer/
    - assets/images/bus/
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
