name: flutterapperadauti
description: A new Flutter application.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <5.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^3.1.12
  cupertino_icons: ^1.0.4
  dio: ^4.0.6
  expandable: ^5.0.1
  firebase_core: ^1.20.0
  firebase_messaging: ^12.0.1
  flutter_form_builder: ^7.1.1
  flutter_local_notifications: ^9.4.0
  flutter_map: ^2.2.0
  flutter_speed_dial: ^6.0.0
  flutter_svg: ^1.0.3
  flutter_widget_from_html: ^0.8.5
  fluttericon: ^2.0.0
  form_builder_image_picker: ^3.1.0
  geolocator: ^9.0.1
  intl: ^0.17.0
  timeline_tile: ^2.0.0
  url_launcher: ^6.0.20
  intro_views_flutter: ^3.2.0
  firebase_storage: ^10.3.4
  selectable_autolink_text: ^2.3.0
  flutter_map_marker_cluster: ^0.5.0
  form_builder_validators: ^8.1.0
  flutter_inappwebview: ^5.3.2
  syncfusion_flutter_charts: ^20.1.48
  get: ^4.6.5
  location: any
  flutter_loadingindicator: ^1.0.1
  card_loading: ^0.2.1
  #dio_http_cache: ^0.3.0
  shared_preferences: ^2.0.15
  flex_color_scheme: ^6.0.1
  octo_image: ^1.0.2
  cached_network_image: ^3.2.2
  flutter_blurhash: ^0.7.0
  auto_size_text: ^3.0.0
  json_annotation: ^4.7.0
  js: ^0.6.4
  searchbar_animation: ^0.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.3
  flutter_native_splash: ^2.1.6
  flutter_lints: ^2.0.1
  json_serializable: ^6.5.2
  build_runner: ^2.3.1
  dependency_validator: ^3.0.0

flutter_native_splash:
  image: assets/logo_images/prop_6.png
  color: "#ffffff"
  color_dark: "#ffffff"
  android: true
  ios: true
  web: false

flutter_email_sender:
  path: ../

flutter_icons:
  image_path_android: "assets/logo_images/app_logo_final.png"
  image_path_ios: "assets/logo_images/app_logo_final.png"
  android: true
  ios: true

flutter:
  assets:
    - assets/
    - assets/images/
    - assets/logo_images/
    - assets/images/volunteer/
    - assets/images/bus/
    - assets/wind/
  uses-material-design: true
