name: flutterapperadauti
description: A new Flutter application.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  add_2_calendar: ^2.1.1
  ai_awesome_message: ^2.0.0
  camera: ^0.9.4+1
  cloud_firestore: ^2.5.3
  cupertino_icons: ^1.0.0
  custom_info_window: ^1.0.1
  dio: ^4.0.0
  dio_http_cache: ^0.3.0
  expandable: ^4.1.4
  firebase_core: ^1.10.0
  firebase_database: ^6.0.0
  firebase_messaging: ^10.0.8
  flutter_form_builder: ^7.0.0
  flutter_icons: ^1.1.0
  flutter_linkify: ^4.1.0
  flutter_local_notifications: ^8.2.0
  flutter_map: ^0.14.0
  flutter_map_marker_popup: ^2.0.0
  flutter_paginator: ^0.0.6
  flutter_speed_dial: ^2.1.1
  flutter_svg: ^0.22.0
  flutter_widget_from_html: ^0.7.0
  fluttericon: ^1.0.7
  form_builder_image_picker: ^2.0.0
  gallery_saver: ^2.0.1
  geolocator: ^7.6.2
  get_it: ^5.0.6
  http: ^0.13.1
  infinite_scroll_pagination: ^2.3.0
  intl: ^0.17.0
  list_tile_switch: ^0.0.2
  overlay_support: ^1.0.5
  path_provider: ^2.0.5
  permission_handler: ^8.1.6
  provider: ^6.0.1
  
  timeline_tile: ^1.0.0
  url_launcher: ^6.0.12
  weather_icons: ^2.0.2
  intro_views_flutter: ^3.2.0
  is_first_run: ^1.0.0
  firebase_image: ^1.0.0
  firebase_storage: ^8.1.3
  flutter_autolink_text: ^1.0.0+1
  flutter_map_marker_cluster: ^0.4.3
  form_builder_validators: ^7.2.0
  flutter_inappwebview: ^5.3.2
  syncfusion_flutter_charts: ^19.4.38
  package_info_plus: ^1.3.0
  auto_size_text: ^3.0.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2   
  flutter_native_splash: ^1.3.2

flutter_native_splash:
  image: assets/logo_images/prop_6.png
  color: "#ffffff"
  color_dark: "#ffffff"
  android: true
  ios: true
  web: false

flutter_email_sender:
  path: ../

flutter_icons:
  image_path_android: "assets/logo_images/app_logo_final.png"
  image_path_ios: "assets/logo_images/app_logo_final.png"
  android: true
  ios: true 

flutter:
  assets:
    - assets/
    - assets/images/
    - assets/logo_images/
    - assets/images/volunteer/
    - assets/images/bus/
  uses-material-design: true
