name: flutterapperadauti
description: A new Flutter application.

publish_to: "none"
version: 3.3.3

environment:
  sdk: ">=3.0.0-218.1.beta <4.0.0"

dependencies:
    flutter:
        sdk: flutter

    # FIREBASE + NOTIFICATIONS
    cloud_firestore: ^4.8.0
    firebase_auth: ^4.6.0
    firebase_core: ^2.13.1
    firebase_messaging: ^14.6.2
    firebase_storage: ^11.2.2
    flutter_local_notifications: ^14.1.1

    # JSON
    json_annotation: ^4.8.1
    json_serializable: ^6.7.0

    # CHARTS
    syncfusion_flutter_charts: ^20.1.48

    # SHARED PREF
    shared_preferences: ^2.0.15
    flutter_secure_storage: ^8.0.0

    # FLUTTER MAP
    flutter_map: ^4.0.0
    flutter_map_marker_cluster: ^1.1.1

    # LOCATION
    location: ^4.4.0
    geolocator: ^9.0.1

    # IMAGE LOADER
    octo_image: ^1.0.2
    flutter_blurhash: ^0.7.0
    cached_network_image: ^3.2.2

    # FORM BUILDER
    form_builder_image_picker: ^4.0.0
    form_builder_validators: ^9.0.0
    flutter_form_builder: ^9.0.0

    # WEB VIEW
    flutter_widget_from_html: ^0.8.5
    flutter_inappwebview: ^5.3.2

    # ANIMATIONS
    lottie: ^2.3.2

    # ICONS
    fluttericon: ^2.0.0

    # OTHER
    flutter_localization: ^0.1.11
    timeline_tile: ^2.0.0
    url_launcher: ^6.0.20
    getwidget: ^3.0.1
    get: ^4.6.5
    intl: ^0.18.0
    js: ^0.6.4
    logger: ^1.1.0
    selectable_autolink_text: ^2.6.0
    dio: ^4.0.6
    expandable: ^5.0.1
    google_fonts: ^4.0.4
    floor: ^1.4.2



dev_dependencies:
    build_runner: ^2.4.4
    dependency_validator: ^3.0.0
    flutter_launcher_icons: ^0.9.3
    flutter_lints: ^2.0.1
    flutter_native_splash: ^2.1.6
    floor_generator: ^1.4.2
    flutter_test:
        sdk: flutter

flutter_native_splash:
    image: assets/logo_images/prop_6.png
    color: "#ffffff"
    color_dark: "#ffffff"
    android: true
    ios: true
    web: false

flutter_icons:
    image_path_android: "assets/logo_images/app_logo_final.png"
    image_path_ios: "assets/logo_images/app_logo_final.png"
    android: true
    ios: true

flutter:
    assets:
        - assets/buttons/
        - assets/drawer/
        - assets/faces/
        - assets/images/
        - assets/images/volunteer/
        - assets/logo_images/
        - assets/wind/
    uses-material-design: true