name: flutterapperadauti
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  add_2_calendar: ^1.4.0
  ai_awesome_message: ^2.0.0
  camera: ^0.7.0+2
  charts_flutter: ^0.10.0
  cupertino_icons: ^1.0.0
  custom_info_window: ^0.0.4
  device_calendar: ^3.1.0
  dio: ^3.0.10
  dio_http_cache: ^0.2.9
  expandable: ^4.1.4
  firebase_core: ^0.7.0
  firebase_database: ^6.0.0
  firebase_messaging: ^8.0.0-dev.15
  fl_chart: ^0.12.3
  flash: ^1.3.2
  flick_video_player: ^0.1.1
  flutter_absolute_path: ^1.0.6
  flutter_form_builder: ^4.2.0
  flutter_icons: ^1.1.0
  flutter_linkify: ^4.1.0
  flutter_local_notifications: ^4.0.1+2
  flutter_mailer: ^1.0.1
  flutter_map: ^0.11.0
  flutter_map_marker_popup: ^0.2.1
  flutter_paginator: ^0.0.6
  flutter_svg: ^0.18.1
  flutter_widget_from_html: ^0.5.0+3
  fluttericon: ^1.0.7
  form_builder_image_picker: ^0.1.2
  gallery_saver: ^2.0.1
  geolocator: ^6.2.1
  get_it: ^5.0.6
  google_maps_flutter: ^1.2.0
  http: ^0.12.0+2
  image_picker: ^0.6.2+3
  infinite_scroll_pagination: ^2.3.0
  intl: ^0.16.1
  mailer: ^3.3.0
  overlay_support: ^1.0.5
  path_provider: ^1.6.11
  permission_handler: ^5.1.0+2
  provider: ^4.0.5
  splashscreen: ^1.2.0
  timeline_tile: ^1.0.0
  url_launcher: ^5.5.0
  video_player: ^0.10.12+2
  weather_icons: ^2.0.2
  webview_flutter: ^1.0.7
  latlng: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.8.0"

flutter_email_sender:
  path: ../

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
flutter_icons:
  #  image_path: "assets/images/icon-128x128.png"
  image_path_android: "assets/logo_images/app_logo_final.png"
  image_path_ios: "assets/logo_images/app_logo_final.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
# The following section is specific to Flutter.
flutter:
  assets:
    - assets/
    - assets/images/
    - assets/logo_images/
    - assets/images/Taxi/
    - assets/images/volunteer/
    - assets/images/council/
    - assets/images/mapIcons/
    - assets/images/bus/
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
