name: flutterapperadauti
description: A new Flutter application.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  add_2_calendar: ^2.1.3
  ai_awesome_message: ^2.2.0
  camera: ^0.9.4+19
  cloud_firestore: ^3.1.12
  cupertino_icons: ^1.0.4
  custom_info_window: ^1.0.1
  dio: ^4.0.6
  dio_http_cache: ^0.3.0
  expandable: ^5.0.1
  firebase_core: ^1.14.1
  firebase_database: ^9.0.11
  firebase_messaging: ^11.2.13
  flutter_form_builder: ^7.1.1
  flutter_local_notifications: ^9.4.0
  flutter_map: ^0.14.0
  flutter_map_marker_popup: ^2.1.2
  flutter_speed_dial: ^5.1.0
  flutter_svg: ^1.0.3
  flutter_widget_from_html: ^0.8.5
  fluttericon: ^2.0.0
  form_builder_image_picker: ^2.0.0
  gallery_saver: ^2.3.2
  geolocator: ^8.2.0
  http: ^0.13.4
  intl: ^0.17.0
  list_tile_switch: ^1.0.0
  path_provider: ^2.0.9
  permission_handler: ^9.2.0
  provider: ^6.0.2
  timeline_tile: ^2.0.0
  url_launcher: ^6.0.20
  intro_views_flutter: ^3.2.0
  is_first_run: ^1.0.0
  firebase_image: ^1.1.1
  firebase_storage: ^10.2.12
  selectable_autolink_text: ^2.3.0
  flutter_map_marker_cluster: ^0.4.4
  form_builder_validators: ^8.1.0
  flutter_inappwebview: ^5.3.2
  syncfusion_flutter_charts: ^20.1.48
  package_info_plus: ^1.4.2
  auto_size_text: ^3.0.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2   
  flutter_native_splash: ^2.1.6

flutter_native_splash:
  image: assets/logo_images/prop_6.png
  color: "#ffffff"
  color_dark: "#ffffff"
  android: true
  ios: true
  web: false

flutter_email_sender:
  path: ../

flutter_icons:
  image_path_android: "assets/logo_images/app_logo_final.png"
  image_path_ios: "assets/logo_images/app_logo_final.png"
  android: true
  ios: true 

flutter:
  assets:
    - assets/
    - assets/images/
    - assets/logo_images/
    - assets/images/volunteer/
    - assets/images/bus/
  uses-material-design: true
