name: floor_repository
description: Dart package which manages firebase firestore
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  logger: ^1.1.0
  floor: ^1.4.2
  firestore_repository:
    path: ../firestore_repository



dev_dependencies:
  flutter_test:
    sdk: flutter
  floor_generator: ^1.4.2
  build_runner: