part of 'app_pages.dart';

abstract class Routes {
  Routes._();
  static const home = _Paths.home;
  static const reportProblem = home + _Paths.reportProblem;
  static const noticeMap = reportProblem + _Paths.reportMap;
  static const townHall = home + _Paths.townHall;
  static const leaders = townHall + _Paths.leaders;
  static const localMeetings = townHall + _Paths.localMeetings;
  static const localCouncil = townHall + _Paths.localCouncil;
  static const localLegislation = townHall + _Paths.localLegislation;
  static const events = home + _Paths.events;
  static const announcements = home + _Paths.announcements;
  static const jobs = announcements + _Paths.jobs;
  static const furniture = announcements + _Paths.furniture;
  static const localAnnouncements = announcements + _Paths.localAnnouncements;
  static const phoneNumbers = home + _Paths.phoneNumberrs;
  static const publicInstitutions = phoneNumbers + _Paths.publicInstitutions;
  static const localDisturbances = phoneNumbers + _Paths.localDisturbances;
  static const localAuthorities = phoneNumbers + _Paths.localAuthorities;
  static const air = home + _Paths.air;
  static const transport = home + _Paths.transport;
  static const train = transport + _Paths.train;
  static const taxi = transport + _Paths.taxi;
  static const bus = transport + _Paths.bus;
  static const trainTimeLine = train + _Paths.trainTimeline;
  static const volunteer = home + _Paths.volunteer;
  static const about = home + _Paths.about;
  static const confidential = home + _Paths.confidential;
  static const partner = home + _Paths.partner;
  static const settings = home + _Paths.settings;
  static const debug = settings + _Paths.debug;
  static const notifications = settings + _Paths.notifications;
  static const onboard = _Paths.onboard;
  static const signIn = _Paths.signIn;
  static const signUp = signIn + _Paths.signUp;
  static const resetPassword = signIn + _Paths.resetPassword;
  static const account = home + _Paths.account;
  static const updatePassword = account + _Paths.updatePassword;
  static const permissionsPage = onboard + _Paths.permissionsPage;
}

abstract class _Paths {
  static const home = '/home';
  static const reportProblem = '/report_problem';
  static const reportMap = '/report_map';
  static const townHall = '/town_hall';
  static const leaders = '/leaders';
  static const localMeetings = '/council_meetings';
  static const localCouncil = '/local_council';
  static const localAuthorities = '/local_authorities';
  static const trainTimeline = '/train_timeline';
  static const settings = '/settings';
  static const debug = '/debug';
  static const notifications = '/notifications';
  static const localDisturbances = '/local_disturbance';
  static const partner = '/partner';
  static const confidential = '/confidential';
  static const phoneNumberrs = '/phone_numbers';
  static const publicInstitutions = '/public_institutions';
  static const transport = '/transport';
  static const train = '/train';
  static const taxi = '/taxi';
  static const bus = '/bus';
  static const volunteer = '/volunteer';
  static const air = '/air';
  static const events = '/events';
  static const localLegislation = '/local_legislation';
  static const announcements = '/announcements';
  static const jobs = '/jobs';
  static const furniture = '/furniture';
  static const about = '/about';
  static const onboard = '/onboard';
  static const signIn = '/sign_in';
  static const signUp = '/sign_up';
  static const resetPassword = '/reset_password';
  static const account = '/account';
  static const updatePassword = "/update_password";
  static const permissionsPage = "/permissions_page";
  static const localAnnouncements = '/localAnnouncements';
}
